# Generated by Django 4.2.10 on 2024-02-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
